

my:
  ds:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_d?useUnicode=ture&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 80
  servlet:
    context-path: /demo1

demo1:
  key: value1

myfile:
  config:
    file-path: d://myfile
    file-type: .jpg
